#!/bin/sh

export TF_NEED_CUDA=1
export TF_NEED_OPENCL=0
export GCC_HOST_COMPILER_PATH=$EBROOTGCC/bin/gcc
export CUDA_TOOLKIT_PATH=$EBROOTCUDA
export TF_CUDA_VERSION=$EBCUDAVERSION
export TF_CUDNN_VERSION=$EBCUDNNVERSION
export CUDNN_INSTALL_PATH=$EBROOTCUDNN
export TF_CUDA_COMPUTE_CAPABILITIES=3.5
export CUDA_PATH=$EBROOTCUDA
export CUDA_COMPUTE_CAPABILITIES=$TF_CUDA_COMPUTE_CAPABILITIES

bazel $*
